// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// `apiKey` ci-dessous n'est PAS un secret d'autorisation (contrairement à une
// clé serveur/service-account) : c'est un identifiant client public, prévu
// par Firebase pour être commité tel quel (voir la doc FlutterFire/Firebase).
// La vraie protection vient des restrictions posées sur cette clé dans
// Google Cloud Console (application Android restreinte par package/SHA-1,
// API restreintes à Firebase Installations/Cloud Messaging) — déjà faites,
// voir le rapport de la tâche "alerte de sécurité GitHub" du 23/09/2026.
// Une alerte de secret scanning GitHub sur ce fichier est un faux positif
// connu, à fermer en "Revoked"/faux positif plutôt qu'à "corriger" ici.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOaVXxTLxT7OWKAmKQXhAZwCJZDCQr94c',
    appId: '1:315814084339:android:3ad14580e856fa12e94186',
    messagingSenderId: '315814084339',
    projectId: 'nexus-jdr',
    storageBucket: 'nexus-jdr.firebasestorage.app',
  );
}
